development:
  adapter: postgresql
  database: quizzer_dev
  username: quizzer_dev
  password: quizzer_dev

test:
  adapter: postgresql
  database: quizzer_test
  username: quizzer_test
  password: quizzer_test
  min_messages: WARNING

production:
  adapter: postgresql
  database: quizzer_production
  username: quizzer_prod
  password: quizzer_prod
